version: '2'
services:
    vb0115application-app:
        image: vb0115application
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://vb0115application-postgresql:5432/Vb0115Application
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    vb0115application-postgresql:
        extends:
            file: postgresql.yml
            service: vb0115application-postgresql
